version: '3.4'

services:
  dockerimage:
    image: ${DOCKER_REGISTRY-}dockerimage
    build:
      context: .
      dockerfile: dockerimage/Dockerfile
    container_name: WeatherApi-container
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
